# RuboCop configuration file
# Disable cyclomatic complexity, ABC size, and method length checks

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
